-- =============================================================================
-- 01_ddl.sql — Modelo relacional em 3FN da Rede Mare Combustiveis
-- SGBD: PostgreSQL 14+
-- Execucao (a partir da raiz do repositorio):
--     psql -d rede_mare -f sql/01_ddl.sql
-- O script e idempotente: recria o schema do zero a cada execucao.
--
-- Politica de exclusao adotada (ON DELETE):
--   CASCADE  -> entidades fracas e associativas (nao existem sem o "dono")
--   RESTRICT -> historico de precos e dominios (apagar exige decisao consciente)
--   SET NULL -> gerente de posto (o posto continua existindo sem gerente)
-- =============================================================================

-- Garante leitura correta de acentos e do simbolo m3 no Windows
SET client_encoding = 'UTF8';

DROP SCHEMA IF EXISTS rede_mare CASCADE;
CREATE SCHEMA rede_mare;
SET search_path TO rede_mare;


-- -----------------------------------------------------------------------------
-- 1. Localizacao (resolve a transitiva municipio -> uf -> regiao)
-- -----------------------------------------------------------------------------
CREATE TABLE regiao (
    sigla_regiao    VARCHAR(2)   PRIMARY KEY,
    nome            VARCHAR(20)  NOT NULL UNIQUE,
    CONSTRAINT ck_regiao_sigla
        CHECK (sigla_regiao IN ('N', 'NE', 'CO', 'SE', 'S'))
);

CREATE TABLE uf (
    sigla_uf        CHAR(2)      PRIMARY KEY,
    sigla_regiao    VARCHAR(2)   NOT NULL,
    CONSTRAINT ck_uf_sigla CHECK (sigla_uf ~ '^[A-Z]{2}$'),
    CONSTRAINT fk_uf_regiao FOREIGN KEY (sigla_regiao)
        REFERENCES regiao (sigla_regiao) ON DELETE RESTRICT
);

CREATE TABLE municipio (
    id_municipio    INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome            VARCHAR(60)  NOT NULL,
    sigla_uf        CHAR(2)      NOT NULL,
    CONSTRAINT uk_municipio_nome_uf UNIQUE (nome, sigla_uf),
    CONSTRAINT fk_municipio_uf FOREIGN KEY (sigla_uf)
        REFERENCES uf (sigla_uf) ON DELETE RESTRICT
);


-- -----------------------------------------------------------------------------
-- 2. Grupo economico (resolve a transitiva cnpj -> cnpj_raiz -> grupo)
-- -----------------------------------------------------------------------------
CREATE TABLE grupo_economico (
    cnpj_raiz       CHAR(8)      PRIMARY KEY,
    nome            VARCHAR(100) NOT NULL,
    CONSTRAINT ck_grupo_raiz CHECK (cnpj_raiz ~ '^[0-9]{8}$')
);


-- -----------------------------------------------------------------------------
-- 3. Gerentes (resolve a transitiva cnpj -> gerente -> telefones)
-- -----------------------------------------------------------------------------
CREATE TABLE gerente (
    id_gerente      INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome            VARCHAR(80)  NOT NULL
);

-- Entidade fraca: um telefone so tem sentido vinculado a um gerente.
CREATE TABLE telefone_gerente (
    id_gerente      INT          NOT NULL,
    telefone        VARCHAR(16)  NOT NULL,
    CONSTRAINT pk_telefone_gerente PRIMARY KEY (id_gerente, telefone),
    CONSTRAINT ck_telefone_formato
        CHECK (telefone ~ '^\([0-9]{2}\) [0-9]{4,5}-[0-9]{4}$'),
    CONSTRAINT fk_telefone_gerente FOREIGN KEY (id_gerente)
        REFERENCES gerente (id_gerente) ON DELETE CASCADE
);


-- -----------------------------------------------------------------------------
-- 4. Posto (entidade central; 1 linha por CNPJ acaba com as grafias divergentes)
-- -----------------------------------------------------------------------------
CREATE TABLE posto (
    cnpj            CHAR(14)     PRIMARY KEY,
    razao_social    VARCHAR(100) NOT NULL,
    tipo_posto      VARCHAR(11)  NOT NULL,
    cnpj_raiz       CHAR(8)      NOT NULL,
    logradouro      VARCHAR(80)  NOT NULL,
    numero          VARCHAR(10)  NOT NULL,
    complemento     VARCHAR(80),
    bairro          VARCHAR(60)  NOT NULL,
    cep             CHAR(9)      NOT NULL,
    id_municipio    INT          NOT NULL,
    id_gerente      INT,
    CONSTRAINT ck_posto_cnpj CHECK (cnpj ~ '^[0-9]{14}$'),
    CONSTRAINT ck_posto_tipo CHECK (tipo_posto IN ('PROPRIO', 'CONCORRENTE')),
    -- A raiz precisa ser coerente com o proprio CNPJ.
    CONSTRAINT ck_posto_raiz CHECK (cnpj_raiz = LEFT(cnpj, 8)),
    CONSTRAINT ck_posto_cep CHECK (cep ~ '^[0-9]{5}-[0-9]{3}$'),
    -- So postos da propria rede possuem gerente cadastrado.
    CONSTRAINT ck_posto_gerente
        CHECK (tipo_posto = 'PROPRIO' OR id_gerente IS NULL),
    -- Chave candidata usada pelas FKs compostas de CONCORRENCIA.
    CONSTRAINT uk_posto_cnpj_tipo UNIQUE (cnpj, tipo_posto),
    CONSTRAINT fk_posto_grupo FOREIGN KEY (cnpj_raiz)
        REFERENCES grupo_economico (cnpj_raiz) ON DELETE RESTRICT,
    CONSTRAINT fk_posto_municipio FOREIGN KEY (id_municipio)
        REFERENCES municipio (id_municipio) ON DELETE RESTRICT,
    CONSTRAINT fk_posto_gerente FOREIGN KEY (id_gerente)
        REFERENCES gerente (id_gerente) ON DELETE SET NULL
);


-- -----------------------------------------------------------------------------
-- 5. Servicos (N:M posto x servico)
-- -----------------------------------------------------------------------------
CREATE TABLE servico (
    id_servico      INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome            VARCHAR(40)  NOT NULL UNIQUE
);

CREATE TABLE posto_servico (
    cnpj            CHAR(14)     NOT NULL,
    id_servico      INT          NOT NULL,
    CONSTRAINT pk_posto_servico PRIMARY KEY (cnpj, id_servico),
    CONSTRAINT fk_ps_posto FOREIGN KEY (cnpj)
        REFERENCES posto (cnpj) ON DELETE CASCADE,
    CONSTRAINT fk_ps_servico FOREIGN KEY (id_servico)
        REFERENCES servico (id_servico) ON DELETE RESTRICT
);


-- -----------------------------------------------------------------------------
-- 6. Concorrencia (auto-relacionamento N:M posto x posto)
-- As colunas tipo_* com valor fixo + FK composta garantem, sem triggers,
-- que o lado "proprio" e um posto da rede e o outro lado e um concorrente.
-- -----------------------------------------------------------------------------
CREATE TABLE concorrencia (
    cnpj_proprio      CHAR(14)    NOT NULL,
    cnpj_concorrente  CHAR(14)    NOT NULL,
    tipo_proprio      VARCHAR(11) NOT NULL DEFAULT 'PROPRIO',
    tipo_concorrente  VARCHAR(11) NOT NULL DEFAULT 'CONCORRENTE',
    CONSTRAINT pk_concorrencia PRIMARY KEY (cnpj_proprio, cnpj_concorrente),
    CONSTRAINT ck_conc_distintos CHECK (cnpj_proprio <> cnpj_concorrente),
    CONSTRAINT ck_conc_tipo_proprio CHECK (tipo_proprio = 'PROPRIO'),
    CONSTRAINT ck_conc_tipo_concorrente
        CHECK (tipo_concorrente = 'CONCORRENTE'),
    CONSTRAINT fk_conc_proprio FOREIGN KEY (cnpj_proprio, tipo_proprio)
        REFERENCES posto (cnpj, tipo_posto) ON DELETE CASCADE,
    CONSTRAINT fk_conc_concorrente
        FOREIGN KEY (cnpj_concorrente, tipo_concorrente)
        REFERENCES posto (cnpj, tipo_posto) ON DELETE CASCADE
);


-- -----------------------------------------------------------------------------
-- 7. Dominios da coleta (integridade de dominio via FK)
-- -----------------------------------------------------------------------------
CREATE TABLE produto (
    id_produto      INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome            VARCHAR(30)  NOT NULL UNIQUE,
    unidade_medida  VARCHAR(12)  NOT NULL,
    CONSTRAINT ck_produto_unidade
        CHECK (unidade_medida IN ('R$ / litro', 'R$ / m³'))
);

CREATE TABLE bandeira (
    id_bandeira     INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome            VARCHAR(40)  NOT NULL UNIQUE
);


-- -----------------------------------------------------------------------------
-- 8. Coleta (cabecalho) e item_coleta (itens) — padrao Pedido / Item_Pedido
-- -----------------------------------------------------------------------------
CREATE TABLE coleta (
    id_coleta       INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cnpj            CHAR(14)     NOT NULL,
    data_coleta     DATE         NOT NULL,
    id_bandeira     INT          NOT NULL,  -- bandeira OBSERVADA no dia
    observacao      VARCHAR(200),
    CONSTRAINT uk_coleta_posto_data UNIQUE (cnpj, data_coleta),
    CONSTRAINT ck_coleta_data
        CHECK (data_coleta BETWEEN DATE '2004-01-01' AND CURRENT_DATE),
    -- Apagar um posto com historico de precos exige decisao explicita.
    CONSTRAINT fk_coleta_posto FOREIGN KEY (cnpj)
        REFERENCES posto (cnpj) ON DELETE RESTRICT,
    CONSTRAINT fk_coleta_bandeira FOREIGN KEY (id_bandeira)
        REFERENCES bandeira (id_bandeira) ON DELETE RESTRICT
);

-- Entidade fraca: o item nao existe sem a coleta.
CREATE TABLE item_coleta (
    id_coleta       INT           NOT NULL,
    id_produto      INT           NOT NULL,
    valor_venda     NUMERIC(6, 3) NOT NULL,
    CONSTRAINT pk_item_coleta PRIMARY KEY (id_coleta, id_produto),
    CONSTRAINT ck_item_valor CHECK (valor_venda > 0 AND valor_venda < 50),
    CONSTRAINT fk_item_coleta FOREIGN KEY (id_coleta)
        REFERENCES coleta (id_coleta) ON DELETE CASCADE,
    CONSTRAINT fk_item_produto FOREIGN KEY (id_produto)
        REFERENCES produto (id_produto) ON DELETE RESTRICT
);


-- -----------------------------------------------------------------------------
-- 9. Indices de apoio as consultas analiticas (FKs nao sao indexadas
--    automaticamente no PostgreSQL)
-- -----------------------------------------------------------------------------
CREATE INDEX ix_coleta_data       ON coleta (data_coleta);
CREATE INDEX ix_item_produto      ON item_coleta (id_produto);
CREATE INDEX ix_posto_municipio   ON posto (id_municipio);
CREATE INDEX ix_conc_concorrente  ON concorrencia (cnpj_concorrente);
